### PR TITLE
add : added two files install.py and py-install.sh#17 added files will allow users to install apps

### PR DESCRIPTION
**Pull request by bhumikadubey**
## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Comment by harshau007** [comment]
Hey @bhumikadubey,
Thanks for the PR, but make the pr on xfce-de branch instead of main since we use that as staging

**Comment by beans9926** [comment]
Have you tested these scripts? If so, can you show the results?

**Comment by bhumikadubey** [comment]
> Have you tested these scripts? If so, can you show the results?

Nope. I was unable to do that

**Comment by Akash6222** [comment]
> > Have you tested these scripts? If so, can you show the results?
> 
> Nope. I was unable to do that

Nvm,
We tested it out and encountered some issues with bugs. Attempting to fix them took longer than expected. As a result, @harshau007, one of our team members, decided to recreate everything from scratch. You can find the updated repository [here](https://github.com/tcet-opensource/tcet-linux-welcome/tree/installer). If you encounter any issues or have suggestions for improvement, please let us know. Additionally, make sure to test it on TCET Linux or any Linux system with XFCE.

**Comment by Akash6222** [comment]
This feature has already been added, so we are closing this issue. We would appreciate it if you could assist us with our other issues as well.

**Pull request closed without merging**
