### PR TITLE
Added Application Installer (BETA)

### PR DESCRIPTION
**Pull request by harshau007**
## Description

Added Installer Application using PyGTK 

## Screenshots (if applicable)

installer

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Review by beans9926 — APPROVED** [review]

**Comment by Akash6222** [comment]
@Rhythm-shahane did you tested ??

**Comment by Rhythm-shahane** [comment]
I have tested Out the Application Installer and It is Working Properly , it installs the The Package (Applications Which Are Mentioned in the Option)

**Comment by Akash6222** [comment]
@harshau007 can you put some screenshots of the Installer

**Comment by harshau007** [comment]
> @harshau007 can you put some screenshots of the Installer

Done

**Review by Akash6222 — APPROVED** [review]
GTG

**Pull request merged**
